image: nfcore/gitpod:latest
tasks:
  - name: Update Nextflow and setup pre-commit
    command: |
      pre-commit install --install-hooks
      nextflow self-update
  - name: unset JAVA_TOOL_OPTIONS
    command: |
      unset JAVA_TOOL_OPTIONS

vscode:
  extensions:
    - nf-core.nf-core-extensionpack # https://github.com/nf-core/vscode-extensionpack
